apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: "2025-05-24T12:12:41Z"
  generation: 4
  labels:
    app: cartservice
  name: cartservice
  namespace: default
  resourceVersion: "1748101425769439001"
  uid: 88775258-93e8-4fc3-951e-8f1e4772308e
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cartservice
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-05-24T15:43:43Z"
      creationTimestamp: null
      labels:
        app: cartservice
    spec:
      containers:
      - image: gcr.io/newproject-460615/cartservice:latest
        imagePullPolicy: Always
        name: cartservice
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-05-24T14:22:24Z"
    lastUpdateTime: "2025-05-24T14:22:24Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-05-24T14:22:24Z"
    lastUpdateTime: "2025-05-24T15:43:45Z"
    message: ReplicaSet "cartservice-98fc896c9" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
