apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "49"
  creationTimestamp: "2025-05-24T12:12:44Z"
  generation: 49
  labels:
    app: checkoutservice
  name: checkoutservice
  namespace: default
  resourceVersion: "1748108454448799024"
  uid: 06c11907-fe40-48d2-8df6-eaadafe0646d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: checkoutservice
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-05-24T17:40:51Z"
      creationTimestamp: null
      labels:
        app: checkoutservice
    spec:
      containers:
      - env:
        - name: SHIPPING_SERVICE_ADDR
          value: shippingservice:50051
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: productcatalogservice:3550
        - name: CURRENCY_SERVICE_ADDR
          value: currencyservice:80
        - name: PAYMENT_SERVICE_ADDR
          value: paymentservice:50051
        - name: EMAIL_SERVICE_ADDR
          value: http://
        - name: CART_SERVICE_ADDR
          value: cartservice:7070
        - name: CHECKOUT_SERVICE_ADDR
          value: checkoutservice:5050
        - name: REDIS_ADDR
          value: :6379
        image: gcr.io/newproject-460615/checkoutservice:latest
        imagePullPolicy: Always
        name: checkoutservice
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-05-24T15:12:07Z"
    lastUpdateTime: "2025-05-24T15:12:07Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-05-24T15:02:20Z"
    lastUpdateTime: "2025-05-24T17:40:54Z"
    message: ReplicaSet "checkoutservice-785cbd9644" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 49
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
