apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2025-05-24T15:34:40Z"
  labels:
    app: currencyservice
  name: currencyservice
  namespace: default
  resourceVersion: "1748100880152255012"
  uid: 36c6bc48-57ce-4de1-8964-d9509b7f279a
spec:
  clusterIP: 34.118.231.37
  clusterIPs:
  - 34.118.231.37
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 7000
  selector:
    app: currencyservice
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
