apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "49"
  creationTimestamp: "2025-05-24T12:12:39Z"
  generation: 49
  labels:
    app: frontend
  name: frontend
  namespace: default
  resourceVersion: "1748108454486431008"
  uid: 5962aa9c-fc4d-4612-bea4-93368c526824
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-05-24T17:40:51Z"
      creationTimestamp: null
      labels:
        app: frontend
    spec:
      containers:
      - env:
        - name: CART_SERVICE_ADDR
          value: cartservice:7070
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: productcatalogservice:3550
        - name: CURRENCY_SERVICE_ADDR
          value: currencyservice:80
        - name: RECOMMENDATION_SERVICE_ADDR
          value: http://recommendationservice:80
        - name: CHECKOUT_SERVICE_ADDR
          value: checkoutservice:5050
        - name: SHIPPING_SERVICE_ADDR
          value: shippingservice:50051
        - name: PAYMENT_SERVICE_ADDR
          value: paymentservice:50051
        - name: EMAIL_SERVICE_ADDR
          value: https://emailservice-xus4gqkkra-uc.a.run.app
        - name: AD_SERVICE_ADDR
          value: http://:9555
        - name: SHOPPING_ASSISTANT_SERVICE_ADDR
          value: adservice:80
        image: gcr.io/newproject-460615/frontend:latest
        imagePullPolicy: Always
        name: frontend
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-05-24T15:20:06Z"
    lastUpdateTime: "2025-05-24T15:20:06Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-05-24T14:22:37Z"
    lastUpdateTime: "2025-05-24T17:40:54Z"
    message: ReplicaSet "frontend-9578d484b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 49
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
