apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: "2025-05-24T16:35:40Z"
  generation: 3
  labels:
    app: paymentservice
  name: paymentservice
  namespace: default
  resourceVersion: "1748108453314687010"
  uid: 9ee2f3bc-6288-4def-9f70-2fc7d23ad9e7
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: paymentservice
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-05-24T17:40:51Z"
      creationTimestamp: null
      labels:
        app: paymentservice
    spec:
      containers:
      - image: gcr.io/newproject-460615/paymentservice:latest
        imagePullPolicy: Always
        name: paymentservice
        ports:
        - containerPort: 50051
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-05-24T16:35:58Z"
    lastUpdateTime: "2025-05-24T16:35:58Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-05-24T16:35:40Z"
    lastUpdateTime: "2025-05-24T17:40:53Z"
    message: ReplicaSet "paymentservice-5bc45f7bb" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
