apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: "2025-05-24T12:12:42Z"
  generation: 3
  labels:
    app: productcatalogservice
  name: productcatalogservice
  namespace: default
  resourceVersion: "1748096974890735003"
  uid: 33027fdc-93e2-41a2-99c7-2b77d36c0033
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: productcatalogservice
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-05-24T14:29:30Z"
      creationTimestamp: null
      labels:
        app: productcatalogservice
    spec:
      containers:
      - image: gcr.io/newproject-460615/productcatalogservice:latest
        imagePullPolicy: Always
        name: productcatalogservice
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-05-24T14:28:27Z"
    lastUpdateTime: "2025-05-24T14:28:27Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-05-24T14:22:38Z"
    lastUpdateTime: "2025-05-24T14:29:34Z"
    message: ReplicaSet "productcatalogservice-6dd78bdfc6" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
