apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
  creationTimestamp: "2025-05-24T12:12:47Z"
  generation: 6
  labels:
    app: shippingservice
  name: shippingservice
  namespace: default
  resourceVersion: "1748101541732719020"
  uid: 369f1f27-35be-4877-9a45-c3b87a872965
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: shippingservice
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-05-24T15:45:38Z"
      creationTimestamp: null
      labels:
        app: shippingservice
    spec:
      containers:
      - image: gcr.io/newproject-460615/shippingservice:latest
        imagePullPolicy: Always
        name: shippingservice
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-05-24T14:28:31Z"
    lastUpdateTime: "2025-05-24T14:28:31Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-05-24T14:22:41Z"
    lastUpdateTime: "2025-05-24T15:45:41Z"
    message: ReplicaSet "shippingservice-846d77c659" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 6
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
